### ISSUE TITLE
icon is blurry

### ISSUE THREAD

**Issue by kindlychung** [asciidoctor/asciidoctor-browser-extension#126]
Maybe I am too picky, but the icon looks unusually blurry:

![](http://i.imgur.com/fq1sm8U.png)

**Comment by Mogztter** [comment]
How did you make this screenshot ?
Files are in `app/img` folder: https://github.com/asciidoctor/asciidoctor-chrome-extension/tree/master/app/img

If you know/want to improve the icon, please do :smile:

**Comment by kindlychung** [comment]
Yeah, I already gave it a go, but not yet quite successful. Maybe later. 😄

**Comment by mojavelinux** [comment]
The key would be to use an SVG, if that is supported.

Keep in mind that we don't yet have an official logo, so this is just a placeholder. However, we could still figure out how to not make it blurry so that when we do have an official logo, that problem is already solved and we have the right specs.

**Comment by Mogztter** [comment]
> The key would be to use an SVG, if that is supported.

Someone already filled an issue for that: https://bugs.chromium.org/p/chromium/issues/detail?id=29683

> You may provide icons of any other size you wish, and Chrome will attempt to use the best size where appropriate. For example, Windows often requires 32-pixel icons, and if the app includes a 32-pixel icon, Chrome will choose that instead of shrinking a 48-pixel icon down. However, you should ensure that all of your icons are square, or unexpected behavior may result.
https://developer.chrome.com/apps/manifest/icons

I think we should also provide a 32px * 32px logo to improve the situation.

**Comment by Mogztter** [comment]
I was wrong:

> Browser action icons can be up to 19 dips (device-independent pixels) wide and high. Larger icons are resized to fit, but for best results, use a 19-dip square icon.

> To properly display icon when screen pixel density (ratio size_in_pixel / size_in_dip) is different than 1, the icon can be defined as set of images with different sizes. The actual image to display will be selected from the set to best fit the pixel size of 19 dip icon. At the moment, the icon set can contain images with pixel sizes 19 and 38.

https://developer.chrome.com/extensions/browserAction

I think we need to provide two more icons (19px and 38px).

**Comment by Mogztter** [comment]
I don't know if the result would be better but we can also use canvas element:
> You can set the icon in two ways: using a static image or using the HTML5 canvas element. Using static images is easier for simple applications, but you can create more dynamic UIs — such as smooth animation — using the canvas element.

**Comment by Mogztter** [comment]
Hopefully we will soon have a beautiful logo: https://github.com/asciidoctor/asciidoctor/issues/48 :grinning:

**Comment by Mogztter** [comment]
Possible work-around: 

>FYI it is possible to use SVG when you set the icon programatically (from the background page), e.g. using
chrome.browserAction.setIcon({ path: 'icon.svg' });
chrome.pageAction.setIcon({ path: 'icon.svg' });
SVG doesn't work for anything declared in the manifest file though.


> If you are looking to change icons in a way that is compatible with both high-DPI and regular displays I found a workaround for my own extension. You can draw on a canvas of size 76x76 for high-DPI and 19x19 for regular. Then when you do setImageData you claim the 76x76 is actually 38. Keep 19 as 19.
Here's my code that handles this: https://github.com/kkamperschroer/Musicality/blob/master/js/background/iconHandler.js

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor-browser-extension/commit/69b4627c45f9a619a85269da675ef3179d43b8c9

Please reopen if the icon is still blury in the next version.
