### ISSUE TITLE
Allow to disable/configure refresh frequency

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-browser-extension#129]
> I put some *.adoc files in nginx , and add location config with types { text/asciidoc adoc; } the plugin will display my doc properly. It is great, but i found it will fresh the URL frequently. I think, the function is helpful when edit a local file. But it will waste resources, if the asciidoc is stable and put in a remote host for others viewing it. Is it possible disable the refresh or lower the frequence

A user from the Chrome Web Store

**Comment by mojavelinux** [comment]
I would think something in the settings like:

Poll for changes:

[all files]
[local files]
[remote files]

(local are files that don't begin with https?://)

**Comment by Mogztter** [comment]
That's a good idea but I think we should also be able to configure the refresh frequency for local files and remote files

 * Refresh frequency
   * local files
     * disable
     * 1sec
     * 2sec
     * 3sec
     * 5sec
     * 8sec
     * custom (type a number of seconds)
   * remote files
     * disable
     * 1sec
     * 2sec
     * 3sec
     * 5sec
     * 8sec
     * custom (type a number of seconds)

**Comment by xnlcasad** [comment]
Hi, we've just hit this issue. We're using asciidoctor to render our documentation and we have many users accesing our documents on a web server hosted on aws. Our aws instance's cpu is maxed out due to this unnecessary traffic generated from the plugin. While we could potentially optimize the instance and the server itself, having the asciidoctor plugin not autorefresh remote pages seems like the most natural solution.

**Comment by Mogztter** [comment]
Hello @xnlcasad, thanks for your feedback.
This feature is on my to-do list 😉 

What do you think about my proposal ?

**Comment by xnlcasad** [comment]
Your proposal looks very reasonable to me. As long as you can have different settings for local and remote files and that the user is able to completely disable the auto refresh feature it should do the work. Do you have any idea when this feature could be available?

To simplify things, a first installment of the feature could simply disable auto reload for remote URLs.

**Comment by Mogztter** [comment]
> To simplify things, a first installment of the feature could simply disable auto reload for remote URLs.

It sounds reasonable but I don't want to remove a "feature" because someone may be using it

> Do you have any idea when this feature could be available?

I will try to work on it tomorrow or this week-end... If you want to give it a try, it will be greatly appreciated 😄

**Comment by xnlcasad** [comment]
Oh, I will be willing to try it starting next week. Just hint me at how to install updated plug-in

**Comment by Mogztter** [comment]
@mojavelinux @xnlcasad I need your opinion on the options page:

![config](https://user-images.githubusercontent.com/333276/37246223-b439b300-24a5-11e8-93a9-a366f26b6787.png)

What do you think about the help messages ?

"Remote files use `http` or `https` protocol."
"Files that don't use `http` or `https` protocol are (considered) local."

**Comment by mojavelinux** [comment]
The technical definition of a URL is a URI that has the http or https protocol. Therefore, I think we can change the label to:

```
Poll for changes to files loaded from URLs
```

with the description:

```
URLs use the http or https protocol
```

Then for local files, we can use the label:

```
Poll for changes to local files
```

with the description:

```
Local files use the file protocol (or no protocol)
```
