### ISSUE TITLE
Extension frequently crashing

### ISSUE THREAD

**Issue by leif81** [asciidoctor/asciidoctor-browser-extension#145]
For the past several months I've seen the extension crash many times. Seemingly while casually browsing the web. In other words when not actually previewing an adoc file. A Chrome notification will appear letting me know the extension has crashed. I usually just dismiss the notification and don't restart the extension until I need it.

I'm using Asciidoctor.js Live Preview 1.5.5.100 in Chrome 56.0.2924.87 on Windows 10.

My Chrome usage is perhaps atypical so I'll describe that. I usually leave Chrome running for days, if not weeks at a time with many tabs (>30) open. It's possible one of those tabs has an adoc open, though I'm fairly certain that's not always the case when a crash happens.

Sorry for lack of info, but I figured I'd file this anyways. If there's a particular log file or info that would help let me know.

**Comment by Mogztter** [comment]
> Sorry for lack of info, but I figured I'd file this anyways. 

No worries, thanks for the report.

> My Chrome usage is perhaps atypical so I'll describe that. I usually leave Chrome running for days, if not weeks at a time with many tabs (>30) open. It's possible one of those tabs has an adoc open, though I'm fairly certain that's not always the case when a crash happens.

When Chrome is crashing, could you please take a screenshot of the task manager ? 
https://support.google.com/chrome/answer/1184722?hl=en

I do think that the extension is only loaded when the URL matches one of this rules: https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/72d49a412cade00f881bb111d5fc1cde014b5eff/app/manifest.json#L22

My guess is that the background may be doing work even if the extension is not used... Could you confirm that Chrome does not crash when the extension is disabled/removed ?

**Comment by leif81** [comment]
> When Chrome is crashing, could you please take a screenshot of the task manager ?
> https://support.google.com/chrome/answer/1184722?hl=en

K, next time.

> Could you confirm that Chrome does not crash when the extension is disabled/removed ?

Ya Chrome remains running.

**Comment by Mogztter** [comment]
I'm doing some testing right now and the extension ressources are pretty stable even when I opened 50 tabs (according to the task manager).
Do you have any custom attributes or JavaScript/Stylesheet configured ?

I'm running on Windows 10 / 1.5.5.100 with unsafe mode, no custom attributes and no JavaScript/Stylesheet configured (I'm using the default asciidoctor stylesheet).

**Comment by Mogztter** [comment]
I think this is because we are reloading the page every 5 seconds. So if the extension is active on a tab the memory will grow indefinitely (even if the tab is not active).

**Comment by leif81** [comment]
> Do you have any custom attributes or JavaScript/Stylesheet configured 

Yes. My custom attributes are: *numbered=true toc=preamble*
No custom JavaScript or Stylesheet though.
I set *Safe mode: safe*

**Comment by mojavelinux** [comment]
I'll add that I have almost the exact usage pattern as @leif81 (so, at least to me, not all that abnormal). I don't see the extension crash very often (if at all), but it doesn't always refresh as expected. There are times when I have to force reload the page to get it to update the content. When this happens again, I'll look for warnings or errors and report them. However, something tells me that perhaps it stops running after one of the conversions fails (perhaps because it caught the content in a transitional state).

**Comment by mojavelinux** [comment]
I have had times when extensions crashed in general with Chrome. This usually stopped after updating Chrome and restoring. There's no question that Chrome occasionally pushes updates that causes problems with extensions from time-to-time (even stable).

**Comment by leif81** [comment]
I haven't seen this crash happen in a long time. I'm using `1.5.5.112`. Closing.
