### ISSUE TITLE
Incorrect escaping of asterisks

### ISSUE THREAD

**Issue by iovuio** [asciidoctor/asciidoctor-browser-extension#162]
**Steps to reproduce**
1. Create document with content
```
= This is a title

This is a description\*.

\*Conditions apply.
```

2. Open file in Chrome having asciidoctor-chrome-extension installed.

**Expected result**

The asterisk properly escaped. No backslash displayed.

**Actual result**

Both backslash and asterisk displayed for the escaped sequences.

**Comment by mojavelinux** [comment]
Do you observe the same behavior when using the main asciidoctor command? If so, this isn't an issue with the Chrome extension but rather with the language parser itself.

This is how the asterisk is escaped for this type of usage in AsciiDoc:

```
= This is a title

This is a description{asterisk}.

{asterisk} Conditions apply.
```

**Comment by Mogztter** [comment]
ping @iovuio

**Comment by Mogztter** [comment]
Hey @iovuio !
Does the answer provided by Dan solved your issue ? Can we close this issue ?

**Comment by iovuio** [comment]
@Mogztter Sorry for the late reply.
Allow me to come back with an answer later today.

**Comment by iovuio** [comment]
Yes, {asterisk} is a good solution.
Closing.
