### ISSUE TITLE
Replace JQuery with zeptojs (or vanilla JavaScript)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-browser-extension#171]
We are really using only a few API of JQuery. I think it's not worth the 85 Ko of minified code (even if, arguably, the size does not really matter that much in a browser extension). 
Also keep in mind that 85 Ko is nothing compared to the MathJax installation bundled inside the extension :neutral_face: 

Anyway I think we shouldn't ship unused code :yum: 

Opinions ? Thoughts ?

**Comment by mojavelinux** [comment]
At this point I think there's a strong case for vanilla JS, esp since you know it's a modern browser.

**Comment by Mogztter** [comment]
@mojavelinux Indeed, I have a pretty big refactoring in progress to use ECMAScript 6 features 😀
