### ISSUE TITLE
could livereload be extended to other dependent local resources like css, js, images?

### ISSUE THREAD

**Issue by rotty3000** [asciidoctor/asciidoctor-browser-extension#193]
These days I'm doing some SVG editing (yes by hand). And it'd be nice when these are attached to adoc files if they could be refreshed like the rest of the doc.

**Comment by Mogztter** [comment]
Hello @rotty3000 
The tricky part is that we need to be aware of these dependent resources to check if they changed (and if they changed, reload/refresh the page).

I'm thinking about adding an option to refresh the page even if the content did not change.
It can be related to https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/129 where you will be able to configure a refresh interval.

What do you think ?

**Comment by rotty3000** [comment]
On the one hand, the proposed solution kills two birds with one stone, which is always a positive.

One the other hand constant reload on a large document means your are often looking at the raw text while the re-rendering happens. As of right now, when I hit refresh on the window for my document I see the raw adoc content for almost a full second before the renderer catches up. So reloading on any short interval is likely to be a terrible use experience.

... but I do understand the complexity of finding all the resources and tracking them ...

**Comment by Mogztter** [comment]
> As of right now, when I hit refresh on the window for my document I see the raw adoc content for almost a full second before the renderer catches up.

Maybe https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/191 could help to speed up the first rendering.

> So reloading on any short interval is likely to be a terrible use experience.

We could potentially find a way to reload and render in the background but you're right this is not perfect.

> ... but I do understand the complexity of finding all the resources and tracking them ...

Using a preprocessor extension could theoretically work but it will require a bit of work...

I will put some more thoughts on it and report back if I get a better idea!
Thanks for your input 😉
