### ISSUE TITLE
Too much padding in highlighted source code block

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-browser-extension#209]
There's too much padding in the container surrounding a highlighted source code block. The problem is that the `<pre>` element is missing the class `highlightjs`, which activates additional styles from the default stylesheet to tighten the spacing.

Using the browser extension:

```html
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-js hljs javascript" data-lang="js">...</code></pre>
</div>
</div>
```

Using the asciidoctor command:

```html
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-js hljs javascript" data-lang="js">...</code></pre>
</div>
</div>
```

**Comment by Mogztter** [comment]
That's weird since we don't explicitly remove `highlightjs` class.. I will look into it :eyeglasses:

**Comment by mojavelinux** [comment]
My understanding is that the extension runs highlight.js itself. If it does this, then it needs to add this class to activate the correct styles from the default stylesheet (and override the poor defaults in highlight.js styles).

**Comment by Mogztter** [comment]
Indeed but we could override the `source-highlighter` attribute since `highlightjs` is the only source highlighter available. If we do that, Asciidoctor core will automatically add the class for us 😄 

https://github.com/asciidoctor/asciidoctor/blob/41bc5dd976efbaf272ade1800a44317515ea79fe/lib/asciidoctor/converter/html5.rb#L594-L596

**Comment by mojavelinux** [comment]
Right you are!

**Comment by Mogztter** [comment]
Thanks Grand Master Yoda :smiley:

**Comment by mojavelinux** [comment]
:joy:
