### ISSUE TITLE
The options page does not have a scrollbar on Chrome 65

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-browser-extension#226]
>Material Design Extensions Page
>The Extensions manager page is receiving an updated look with Chrome 65. Accessible in the Omnibox under “Manage Extensions”, this new layout offers the same functionality with enhanced organization and modern styling.

https://productforums.google.com/forum/#!topic/chrome/N1Go1_LkQKk

"modern styling" but the new options page looks really bad! I'm not sure if it's a bug or a feature... Any way we will need to update the stylesheet because the options page is unusable on Chrome 65.

![options-page-noscroll](https://user-images.githubusercontent.com/333276/37995145-b7c65854-3213-11e8-9089-e95f086baeac.PNG)

![options-page](https://user-images.githubusercontent.com/333276/37995148-b8f7c410-3213-11e8-81df-f8bfefbb839d.PNG)

**Comment by Mogztter** [comment]
Looks like a bug and they are working on it: https://bugs.chromium.org/p/chromium/issues/detail?id=820876#c7

**Comment by Mogztter** [comment]
As a workaround, go to `chrome://flags/#enable-md-extensions` and disable this option.

**Comment by Mogztter** [comment]
Chrome 66 released today with a fix!

**Comment by mojavelinux** [comment]
Aha. That answers my other question. Great news then!
