### ISSUE TITLE
Unresolved directive in <stdin> - include::

### ISSUE THREAD

**Issue by pbrentlinger** [asciidoctor/asciidoctor-browser-extension#240]
My main.adoc and ch1.adoc are in the same file.

```

include::ch1.adoc[]

== Attributes

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}
docdir:: {docdir}
```
![adocinclude_failure](https://user-images.githubusercontent.com/1392583/38952997-61eed99c-431b-11e8-8ce4-26400c8c0de5.jpeg)

This works fine with asciidoctor and asciidoctor-pdf.
similar to https://github.com/asciidoctor/asciidoctor-firefox-addon/issues/21

**Comment by Mogztter** [comment]
Hello @pbrentlinger 
Are you using Firefox ?
I'm pretty sure this issue is already fixed on master. I will release a new version in a few days :wink:

**Comment by Mogztter** [comment]
I was wrong this issue is still present on master. I've just submitted a pull request to fix it :bug:

**Comment by Foadsf** [comment]
I have Firefox Quantum 69.0.3 on Windows 10 version 1809 and the AsciiDoc plugin can't render the `include::foo.bar[]` directive:

> Unresolved directive in baz.adoc - include::foo.bar[]

the Document can be seen [here](https://gist.github.com/Foadsf/44fe9b5e2bcb02b22392adf6d8f7a871).

**Comment by Mogztter** [comment]
I think it's related to https://github.com/asciidoctor/asciidoctor-browser-extension/issues/302

Could you please try this workaround: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/302#issuecomment-524569613
