### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by gernotpokorny** [asciidoctor/asciidoctor-browser-extension#255]
Why [syntax highlightning](https://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks) is not working in the chrome extension live-preview? I have the 'asciidoctor' stylesheet enabled in the options. I tested it with the examples from the [documentation](https://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks).

**Comment by Mogztter** [comment]
You should enable source highlighting using `:source-highlighter: highlight.js`

https://asciidoctor.org/docs/user-manual/#enabling-source-highlighting

Highlight.js is the only source highlighter available in the browser extension.
Let me know if it works for you.

**Comment by gernotpokorny** [comment]
Works! Thank you very much.

**Comment by gernotpokorny** [comment]
The Writer's Guide is linked first on the [website](https://asciidoctor.org/) and on [Google](https://www.google.at/search?q=asciidoc&oq=ascii&aqs=chrome.0.69i59l3j69i60l3.952j0j7&sourceid=chrome&ie=UTF-8). So I read that first. Probably many people will go that route. Then they miss that information at [Listing and source code blocks](https://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks) in the Writer's Guide. Do you think we should add a NOTE: or IMPORTANT: in the Writer's Guide and link to the [description in the User's Manual](https://asciidoctor.org/docs/user-manual/#source-code-blocks)?

**Comment by Mogztter** [comment]
> Works! Thank you very much.

👍 

> The Writer's Guide is linked first on the website and on Google. So I read that first. Probably many people will go that route. Then they miss that information at Listing and source code blocks in the Writer's Guide. Do you think we should add a NOTE: or IMPORTANT: in the Writer's Guide and link to the description in the User's Manual?

@mojavelinux and @graphitefriction are working on the new documentation site (based on Antora). You can see a preview at: https://asciidoctor-docs.netlify.com
The migration was a bit delayed but relatively soon https://asciidoctor.org/docs/ will be replaced by https://asciidoctor-docs.netlify.com

In the new documentation site the section which relates to source highlighting mentions the `:source-highlighter:`: https://asciidoctor-docs.netlify.com/asciidoc/1.5.7/source/source/

So I think it's just a matter of time before our documentation site becomes more consistent 😉

**Comment by Mogztter** [comment]
I'm closing this issue, if you do have more questions, feel free to ask on Gitter 😄
