### ISSUE TITLE
Update logo in firefox and opera addon pages

### ISSUE THREAD

**Issue by 5paceToast** [asciidoctor/asciidoctor-browser-extension#268]
They are currently outdated.
This is a reminder, as requested in gitter.

**Comment by LinoMLT** [comment]
But now Opera addon page opens in French.

**Comment by Mogztter** [comment]
Publishing a new update on Opera store used to be fast but it's been 30 days and I still haven't gotten a reply (for a simple logo update)...

@LinoMLT nice catch! I don't think it's related to the logo update. The URL on the README contains `fr` if you want to fix it feel free to open a new pull request 😉

**Comment by Mogztter** [comment]
And done 🚀
