### ISSUE TITLE
Align inconsistent between asciimath, latexmath, stem blocks 

### ISSUE THREAD

**Issue by iovuio** [asciidoctor/asciidoctor-browser-extension#272]
A `[latextmath]` block has the nice feature of centering its content.
Migrating `[latexmath]` blocks to `[stem]` blocks left aligns the block content.
Also, the `[asciimath]` also left aligns.

Please see content below. Only second block is centered.
```
= Math formulae
:stem:

.asciimath in [asciimath] block
[asciimath]
++++
sum_(i=0)^n i = (n(n+1))/2
++++

.latexmath in [latextmath] block
[latexmath]
++++
\int_0^1 x^n= \frac{1}{n+1}
++++

.latexmath in [stem] block
[stem]
++++
\int_0^1 x^n= \frac{1}{n+1}
++++
```
Some suggestions
----

1. Should stem, asciimath, latexmath align consistently, all center or all left align? I believe yes.
2. Should centering be the default align for stem, asciimath, latexmath blocks? I believe yes. We can use inlines on a new line to achieve the left align.
3. Should there be a way to override the default? That would be great!
```
[stem,align="left|right|center"]
++++
0 ^^ 1 = 0
++++

**Comment by mojavelinux** [comment]
It would be nice if they were consistent. But how they are aligned / laid out is not handled by Asciidoctor. It's handled by MathJax. And for some reason, MathJax does it differently.

**Comment by iovuio** [comment]
Indeed, it seems that MathJax has two notation for TeX:

* *displayed mathematics* (centered, clear both, what I referred to above as _block_)
* *in-line mathematics*

an only one mode for AsciiMath, which seems to be the inline version. Achieving centered, clear-both as suggested in the docs using styled paragraphs

```
<p style="text-align:center">
  `x = (-b +- sqrt(b^2-4ac))/(2a) .`
</p>
```

Closing issue.

**Comment by iovuio** [comment]
For reference purposes, the linked upstream issue report https://github.com/mathjax/MathJax/issues/2128

**Comment by iovuio** [comment]
Davide of MathJax offered a solution that makes it possible for downstreamers to control how the blocks are displayed. Pull request sent.

**Comment by mojavelinux** [comment]
I found an even simpler way to do this (since we can rely on the structure of our own HTML).

```js
MathJax.Hub.Register.StartupHook("AsciiMath Jax Ready", function () {
  MathJax.InputJax.AsciiMath.postfilterHooks.Add(function (data, node) {
    if ((node = data.script.parentNode) && (node = node.parentNode) &&
        node.classList.contains('stemblock')) {
      data.math.root.display = "block";
    }
    return data;
  });
});
```
