### ISSUE TITLE
Upgrade MathJax to 2.7.6

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-browser-extension#274]
https://github.com/mathjax/MathJax/releases/tag/2.7.6

**Comment by Mogztter** [comment]
Latest version is now 2.7.6.
For reference, version 3.0 of MathJax is also available but we will probably need to upgrade carefully:

> Version 3.0 of MathJax is a complete rewrite of MathJax from the ground up, and its usage and configuration is significantly different from that of MathJax version 2. 

http://docs.mathjax.org/en/latest/

**Comment by mojavelinux** [comment]
> For reference, version 3.0 of MathJax is also available but we will probably need to upgrade carefully:

I'm excited, but also nervous ;) If we can get it to work with no change to the output document, we could do it in Asciidoctor 2.1. Otherwise, it should happen with Asciidoctor 3.

**Comment by Mogztter** [comment]
I did some tests this morning but AsciiMath does not work great:


![mathjax-3](https://user-images.githubusercontent.com/333276/66383107-b1587a80-e9bc-11e9-9dfc-ff4ec2f21134.png)

As you can see the formula is replaced but the text is still present.
For reference I'm using the following configuration:

```js
MathJax = {
  tex: {
    inlineMath: [['\\(', '\\)']],
    displayMath: [['\\[', '\\]']],
    tags: 'none'
  },
  options: {
    ignoreHtmlClass: 'nostem|noasciimath'
  },
  asciimath: {
    delimiters: [['\\$', '\\$']]
  },
  loader: {load: ['input/asciimath', 'output/chtml', 'ui/menu']}
}
```

> The AsciiMath input jax has not yet been fully ported to version 3. Instead, the AsciiMath component uses the version 2 AsciiMath input jax together with some of the legacy version 2 code patched into the version 3 framework. This is less efficient, and somewhat larger, than a pure version-3 solution would be, and it can complicate the configuration process. A full version-3 port of AsciiMath is planned for a future release.


http://docs.mathjax.org/en/latest/input/asciimath.html

**Comment by Mogztter** [comment]
It seems related to the `\$` delimiter: https://github.com/mathjax/MathJax-src/issues/364

**Comment by Mogztter** [comment]
@mojavelinux Are you willing to use another delimiter to avoid conflicts ?

**Comment by Mogztter** [comment]
@mojavelinux I've managed to get MathJax 3 working without any major changes. Should I open a pull request in https://github.com/asciidoctor/asciidoctor ?
Having said that maybe some advanced features are not yet available in MathJax 3: 

- http://docs.mathjax.org/en/latest/upgrading/v2.html#v2-not-ported
- http://docs.mathjax.org/en/latest/upgrading/v2.html#v2-not-available
