### ISSUE TITLE
Firefox disables the extension due to "security reasons" (signing?) 

### ISSUE THREAD

**Issue by fabrizioiannetti** [asciidoctor/asciidoctor-browser-extension#286]
Hi, I'm using firefox 66 on ubuntu 18.04 and (I guess after an update) the extension was disabled automatically.

My current workaround is to set `xpinstall.signatures.required` to `false` in `about:config`

it still says

> Asciidoctor.js Live Preview could not be verified for use in Firefox. Proceed with caution.

but I can use it.

**Comment by Mogztter** [comment]
Thanks for your report (and the workaround).

Did you install the extension through  https://addons.mozilla.org ?

As far as I know the new version has been approved (and signed). I will check the developer dashboard and let you know if I found something.

**Comment by mojavelinux** [comment]
This is a global Firefox issue that is affecting all plugins.

**Comment by Mogztter** [comment]
Indeed, I just found the link too while reading my twitter feed :wink:

**Comment by fabrizioiannetti** [comment]
Ah OK, sorry. It's just that yours is the only extension I use ;-)

**Comment by Mogztter** [comment]
It should be fixed now:

> We released Firefox 66.0.4 for Desktop and Android, as well as Firefox 60.6.2 ESR that re-enables extensions. For more information, please read the update on https://t.co/kZ9vOlN5hu Thank you for being patient with us! Thanks to everyone working on it!

https://twitter.com/mozamo/status/1125146829660786688?s=03
