### ISSUE TITLE
regression? inter-document cross references not working anymore (outfilesuffix is wrong)

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor-browser-extension#293]
In Chrome when the HTML created for inter-document cross reference was using the `.adoc` extension and not `.html`.
This was working correctly for me since years.

Example:

```adoc
This link to <<page2.adoc#, page 2>> is not working anymore.
```

Is rendered to:

```html
<div id="content"><div class="paragraph">
<p>This link to <a href="page2.html">page 2</a> is not working anymore.</p>
</div></div>
```

Tested with:

* Version: 2.1.0
* Chrome: Version 75.0.3770.100

---

Workaround:

Set `outfilesuffix` to `.adoc` in the extension configuration.

<img width="391" alt="Screenshot 2019-07-10 at 14 30 55" src="https://user-images.githubusercontent.com/1222165/60969249-64aec600-a31f-11e9-8618-69535e3fa8d3.png">

---

Reference: https://asciidoctor.org/docs/user-manual/#inter-document-cross-references
(original issue https://github.com/asciidoctor/asciidoctor-browser-extension/pull/48)

**Comment by Mogztter** [comment]
I think it's related to: https://github.com/asciidoctor/asciidoctor-browser-extension/pull/287
I didn't thought about cross references... I think `outfilesuffix=.adoc` should be the default.
@mojavelinux what do you think ?

If you want you can open a pull request to fix it: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/8bc02891479def4a999fbf802074bfba01b4279f/app/js/renderer.js#L313
Also make sure to update the test: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/8bc02891479def4a999fbf802074bfba01b4279f/spec/asciidocify-rendering-spec.js#L17

**Comment by jmini** [comment]
Thank you a lot for the fix!
