### ISSUE TITLE
Mathjax doesn't works in Firefox 69.0.2 (Windows 8.1)

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor-browser-extension#306]
Let's say we have some test file:

```
= Test file
:nofooter:
:stem: latexmath

stem:[\sin(x^2)]
```

In browser we see the following:

![image](https://user-images.githubusercontent.com/33900895/66325638-42cddb00-e930-11e9-858e-12f246098c0e.png)

It's okay. Please do nothing and wait for several seconds (approx 25 seconds).

You will see:

![image](https://user-images.githubusercontent.com/33900895/66325716-68f37b00-e930-11e9-96ae-3688e6012ffb.png)

Please fix this and update mathjax version.

Unfortunately this error doesn't produce anything in devtools console. The only I found is:

```
TypeError: c.FONTDATA.FONTS.MathJax_Main[8212][5] is undefined
```

but this error is shown before math processing error.

Best regards,
Andrey.

**Comment by sindzicat** [comment]
Yes, it's right. I'm about extension for Firefox.

**Comment by sindzicat** [comment]
The problem is that something blocks some Mathjax filex in Firefox. Any ideas to fix this?

**Comment by Mogztter** [comment]
Firefox 68 introduced a strict security policy: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/68#Security 

Can you please try this procedure: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/302#issuecomment-524569613 ?

**Comment by sindzicat** [comment]
`privacy.file_unique_origin` is `false` already. Sorry, this didn't helped.

**Comment by sindzicat** [comment]
By the means, I switched `privacy.file_unique_origin` to false, because `include` directive didn't work. I found you comment and made this change.

**Comment by sindzicat** [comment]
I found a workarround:

1. `about:config`
2. type `policy` in search field and wait for a few seconds
3. backup value of field `extensions.webextensions.default-content-security-policy` in text file.
4. copy value of field `extensions.webextensions.base-content-security-policy` to value of field `extensions.webextensions.default-content-security-policy`. In my case I copied `script-src 'self' https://* moz-extension: blob: filesystem: 'unsafe-eval' 'unsafe-inline'; object-src 'self' https://* moz-extension: blob: filesystem:;`

After these manipulations all works fine.

That means that problem is in content security policy. It seems to me you should edit extension manifest to fix this problem.

**Comment by sindzicat** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by sindzicat** [comment]
Just found (maybe, this will be usefull):

Firefox does not support 'http://127.0.0.1' or 'http://localhost' as script sources: they must be served over HTTPS.

**Comment by sindzicat** [comment]
Now I found what causes this problem.

I got log again:

```
MathJax.Message.Log()
"
Loading [MathJax]/config/TeX-MML-AM_HTMLorMML.js
Loading [MathJax]/jax/output/HTML-CSS/jax.js
Loading [MathJax]/jax/output/HTML-CSS/fonts/TeX/fontdata.js
Loading [MathJax]/jax/output/HTML-CSS/imageFonts.js
Loading [MathJax]/fonts/HTML-CSS/TeX/png/imagedata.js
File failed to load: moz-extension://a1ee119f-6f8c-4372-b219-7f46295a6157/vendor/MathJax/fonts/HTML-CSS/TeX/png/imagedata.js
File failed to load: moz-extension://a1ee119f-6f8c-4372-b219-7f46295a6157/vendor/MathJax/jax/output/HTML-CSS/jax.js
Error preparing HTML-CSS output (preProcess)
File failed to load: moz-extension://a1ee119f-6f8c-4372-b219-7f46295a6157/vendor/MathJax/jax/output/HTML-CSS/imageFonts.js"
```

The first problem file is `moz-extension://a1ee119f-6f8c-4372-b219-7f46295a6157/vendor/MathJax/fonts/HTML-CSS/TeX/png/imagedata.js` I tried to open this link in Firefox and saw that there is no such file.

Then I found extension xpi file, copied it on Desktop and opened this file via 7zip as archive. I found  that folder `png` is really missing in `vendor/MathJax/fonts/HTML-CSS/TeX/`. So this is definitely error of this extension.

![image](https://user-images.githubusercontent.com/33900895/66372028-a34f2d80-e9ad-11e9-9813-2b24782ccc5b.png)

Please update Mathjax to the latest 2.7.6 version and pack it correctly.

**Comment by Mogztter** [comment]
> Then I found extension xpi file, copied it on Desktop and opened this file via 7zip as archive. I found that folder png is really missing in vendor/MathJax/fonts/HTML-CSS/TeX/. So this is definitely error of this extension.

We do not include the whole MathJax distribution (33Mb).
The browser extension (without MathJax) is only a few Mb and I don't want to add more than 30Mb just for one feature.

Also, please note that the package hasn't changed in years and, as far as I know, it was working fine in Firefox 68 (and it's also working fine in Chrome). So something changed in Firefox.

> Please update Mathjax to the latest 2.7.6 version and pack it correctly.

There's already an issue to upgrade to MathJax 2.7.6: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/274

I will try to include the whole Mathjax distribution in extension to troubleshoot this issue on Firefox.

**Comment by sindzicat** [comment]
Surprisingly, Chrome extension doesn't have this file too. But log is difference slightly:

```
Loading [MathJax]/config/TeX-MML-AM_HTMLorMML.js
Loading [MathJax]/jax/output/HTML-CSS/jax.js
Loading [MathJax]/jax/output/HTML-CSS/fonts/TeX/fontdata.js
Loading web-font TeX/Math/Italic
Loading [MathJax]/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/Main.js
Loading web-font TeX/Main/Regular"
```

So it's possible for MathJax to load web fonts in Chrome. That's why I see first error `TypeError: c.FONTDATA.FONTS.MathJax_Main[8212][5] is undefined` in Firefox.

According [documentation](https://docs.mathjax.org/en/v2.7-latest/installation.html#firefox-and-local-fonts) this is an expected behavior. Hm...

**Comment by sindzicat** [comment]
I downloaded and installed MathJax fonts from [here](https://github.com/mathjax/MathJax/tree/82083b37b7cf184cf80e2fca12f612704df92b08/fonts/HTML-CSS/TeX/otf) and restarted Firefox. This solved my problem.

Maybe you need to update documentation. Also it seems to me that such problem will not presented in MathJax 3.0.

**Comment by sindzicat** [comment]
@Mogztter, sorry, I didn't see your answer. You don't need to include full MathJax distro in extension. Just add in documentation, that Firefox users need install Mathjax font on their computers.

**Comment by Mogztter** [comment]
No worries.
MathJax should work out of the box, I will see what I can do to please Firefox :wink:

**Comment by Mogztter** [comment]
Using MathJax 3+ seems to resolve this issue.

**Comment by Mogztter** [comment]
I've just released and published version 2.3.0: https://github.com/asciidoctor/asciidoctor-browser-extension/releases/tag/v2.3.0
Could you please confirm that this issue is now resolved (using MathJax 3.0.0) ?

Also the rendering should be faster :zap:

**Comment by sindzicat** [comment]
Just tested in Firefox. All works fine! :+1: Many thanks!

Also, rendering is very fast now!

**Comment by Mogztter** [comment]
I'm glad to hear that!
Thanks for your report 🧾
