### ISSUE TITLE
Make asciidoctor-browser-extension avaliable in vim editor.

### ISSUE THREAD

**Issue by QMHTMY** [asciidoctor/asciidoctor-browser-extension#313]
I am wondering if I can edit an asciidoc file in vim editor while the rendered html file is showing in web browser like Chrome, Firefox? I mean that when I open an asciidoc file by vim, the vim open the browser and show the rendered html.

**Comment by Mogztter** [comment]
> I am wondering if I can edit an asciidoc file in vim editor while the rendered html file is showing in web browser like Chrome, Firefox?

Yes you can that basically what I'm using.

> I mean that when I open an asciidoc file by vim, the vim open the browser and show the rendered html.

You want to open the current file in a browser from vim?
https://stackoverflow.com/questions/8708154/open-current-file-in-web-browser-in-vim

**Comment by AXGKl** [comment]
For live editing this comes also handy:

```vim
function! s:autosave(enable)
  augroup autosave
    autocmd!
    if a:enable
      autocmd TextChanged,InsertLeave <buffer>
            \  if empty(&buftype) && !empty(bufname(''))
            \|   silent! update
            \| endif
    endif
  augroup END
endfunction

command! -bang AutoSave call s:autosave(<bang>1)
```
-> After `:AutoSave` you get your page updated in the browser after each edit action.

**Comment by QMHTMY** [comment]
I got, Thanks a lot!

**Comment by Mogztter** [comment]
Thanks @AXGKl for providing a solution, closing :octopus:
