### ISSUE TITLE
How to get the same HTML structure as from Chrome extension?

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor-browser-extension#314]
Hello.

Let's say we have the following file:

```adoc
= Title 
:nofooter:
:toc:

++++
<style>
body {
    background-color: #f5f5f5;
    background-image: url(https://cdn.pixabay.com/photo/2016/02/11/01/53/wall-paper-1193001_960_720.jpg);
}

body > #content {
    background-color: white;
    padding: 0.5rem 3rem;
    border: 1px solid #ddd;
    box-shadow: 0 1px 5px #ccc;
    min-width: 400px;
}

/* Заголовки */
h1, h2, h3, h4, h5, h6 {
    color: rgba(0, 0, 0, 0.8);
    font-weight: bold;
}

#content h1 {
    text-align: center;
}
</style>
++++

== Section 1

Some text

== Section 2

Some text
```
When I render this file using asciidoctor.js chrome extension, I get the following HTML structure:

![image](https://user-images.githubusercontent.com/33900895/72830486-e2219e80-3c91-11ea-8b71-6a29b0442467.png)

And page looks good:

![image](https://user-images.githubusercontent.com/33900895/72830511-efd72400-3c91-11ea-8da1-dfb486398e45.png)

When I try Asciidoctor or Asciidoctor.js via Node.js, I got the different HTML structure:

![image](https://user-images.githubusercontent.com/33900895/72830559-054c4e00-3c92-11ea-8c12-136ef0560cf5.png)

And result don't looks so good:

![image](https://user-images.githubusercontent.com/33900895/72830586-139a6a00-3c92-11ea-9dfc-10b7bd6742a0.png)

How can I make Asciidoctor.js to create the same HTML, as chrome extension?

**Comment by Mogztter** [comment]
For reference, could you please share how do you invoke Asciidoctor.js?
The browser extension is using an embeddable document: https://asciidoctor.org/docs/user-manual/#embeddable-output

If you want to control the output you could also use a custom converter.

**Comment by sindzicat** [comment]
I just used `asciidoctor-win.exe` from [here](https://github.com/asciidoctor/asciidoctor.js/releases/tag/v2.0.3).

**Comment by mojavelinux** [comment]
As @Mogztter points out, Asciidoctor can produce either a standalone document or an embedded document. The difference is mostly that the standalone document has the framing of a full HTML page, including the header and footer, wrapped around the content. However, due to how that layout is done, there are slight differences in how the document title is displayed. The embeddable document outputs the doctitle as a simple h1 heading, whereas the standalone document wraps it in a block (more formal)

If you want to match the output the chrome extension produces, you can create the embedded document, then add the HTML framing that goes around it.

If you want to customize the output of the standalone document, you can do so using custom templates or by extending the converter and overriding the node convert methods. (See https://github.com/asciidoctor/asciidoctor.org/issues/80).

**Comment by Mogztter** [comment]
> I just used asciidoctor-win.exe from here.

By default the CLI will produce a standalone document so you need to do:

```
asciidoctor-win.exe doc.adoc --embedded -a showtitle
```

**Comment by sindzicat** [comment]
Tried `--embeded` and `--standalone`. The same output (`body > #header and #content`). Are you sure that `--standalone` should get the same HTML output as Chrome extension produces? Maybe I need pass anything else?

**Comment by mojavelinux** [comment]
`--standalone` is not a valid flag. Only `--embedded` is. It switches the converter from producing standalone to producing embedded output.

Can you share which version of asciidoctor you are using? `asciidoctor -v`

**Comment by sindzicat** [comment]
```
Sindzicat@AGSH E:\_temp
> "c:\Portable Apps\asciidoctor-win.exe" -v
Asciidoctor.js 2.0.3 (Asciidoctor 2.0.9) [https://asciidoctor.org]
Runtime Environment (node v12.2.0 on win32)
CLI version 2.0.1
```

**Comment by mojavelinux** [comment]
Let's assume you have the following document named test.adoc:

```
= Article Title

Body of article.
```

If you run that using:

```
asciidoctor-win.exe doc.adoc -e -a showtitle test.adoc
```

You will get:

```
<h1>Article Title</h1>
<div class="paragraph">
<p>Body of article.</p>
</div>
```

---

Given it seems you are just getting used to Asciidoctor, it's strange that you are starting with the pre-built binaries for Asciidoctor.js. Those are rather experimental at the moment (as I understand it). I would recommend starting with the Asciidoctor Ruby gem.

**Comment by Mogztter** [comment]
> Given it seems you are just getting used to Asciidoctor, it's strange that you are starting with the pre-built binaries for Asciidoctor.js. Those are rather experimental at the moment (as I understand it). I would recommend starting with the Asciidoctor Ruby gem.

The pre-build binaries are quite recent but Asciidoctor.js CLI is pretty stable at this point and has the same set of features as the Asciidoctor Ruby gem.
If something is missing please report an issue on GitHub.

> Tried --embeded and --standalone

You made a typo, it's `--embedded` and as pointed by @mojavelinux `--standalone` is not a valid flag.
I can also confirm that `asciidoctor-win.exe doc.adoc --embedded -a showtitle` is working as expected (unless I'm missing something).

**Comment by mojavelinux** [comment]
>  Asciidoctor.js CLI is pretty stable

Absolutely. I was referring to the pre-built binaries, which really haven't been proven by users yet since they are so new.

**Comment by sindzicat** [comment]
I installed ruby version of Asciidoctor.

![image](https://user-images.githubusercontent.com/33900895/72980512-c500e300-3deb-11ea-8adc-8a233eec00ee.png)

My result:

![image](https://user-images.githubusercontent.com/33900895/72980585-eeba0a00-3deb-11ea-9d7c-3c75be2f9882.png)

`<body>` doesn't have class "article" and there is no `<div id="content">`. 
This is an HTML, generated by extension:

![image](https://user-images.githubusercontent.com/33900895/72980723-2923a700-3dec-11ea-9754-7d78d98da07a.png)

Sorry, It's seems I'm very stupid today...

**Comment by mojavelinux** [comment]
That's exactly what is expected. You have successfully generated the embedded HTML. Now, you have to wrap that HTML in the same HTML that the Chrome extension uses. The asciidoctor command does not do that for you.

Understand that what you are asking for is custom HTML output. There is a way to accomplish that purely with Asciidoctor using custom templates, and extended converter, or an extension. But you aren't going to get exactly what the Chrome extension makes using the asciidoctor command alone.

**Comment by sindzicat** [comment]
So, Chrome extension puts generated HTML in `div#content`? Am I right?

**Comment by mojavelinux** [comment]
That is exactly right.

(Btw, when you view the tree of the embedded document in the inspector, the html and body tags are being added by the browser...they aren't really there).

**Comment by sindzicat** [comment]
Oh, I see now. I know Python, so now I can write own wrapper for this.

**Comment by sindzicat** [comment]
@mojavelinux, @Mogztter, many thanks!

**Comment by mojavelinux** [comment]
:+1:
