### ISSUE TITLE
version 2.4.0 doesn't work in Firefox 72.0.1 on Linux

### ISSUE THREAD

**Issue by r-pf** [asciidoctor/asciidoctor-browser-extension#322]
Hi,

since today the add-on doesn't works with aodc-files. 
No formatting will be performed - only the source-text of the adoc-file will be shown.
Asciidoctor.js Live Preview was updated to today to 2.4.0.

Rollback to 2.3.1 => it works again
Installation of 2.4.0 => it doesn't work.
Rollback to 2.3.1 again => it works again.

So I think there is a failure in 2.4.0 (when installed in Firefox 72.0.1 on Linux)

Sincerely
  Rudolf Pfister

**Comment by Mogztter** [comment]
Hi and thanks for your report.
I will try to reproduce this issue in my machine. Could you please open the developer console and copy the output ?

Thanks!

**Comment by Mogztter** [comment]
It seems that Firefox does not allow to fetch the file from the background script for "security reasons" and Chrome does not allow to fetch the file from the content script for "security reasons"... 

> Security Error: Content at moz-extension://1d91c46a-9d2b-41f0-a05c-856aceb760b4/\_generated_background_page.html may not load or link to file:///path/to/doc.adoc?_=1582787196071.

**Comment by r-pf** [comment]
Hi,
the output of the developer console is:

"Die Zeichenkodierung des Reintext-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Transferprotokoll deklariert werden oder die Datei muss eine Byte-Order-Markierung als Kodierungssignatur verwenden."

Greetings

**Comment by r-pf** [comment]
Hi,
in the attacht zip-File are two *.adoc.
Using HelloWorld.adoc the message mentioned above occurs.
Using HelloWorld_BOM.adoc (is like HelloWorld.adoc but with prepended UTF8-BOM) no message occurs. 
Both files uses only US-ASCII-characters (except of course the BOM-bytes)
For both files no formatted preview appears.

Greetings

[HelloWorld_adocs.zip](https://github.com/asciidoctor/asciidoctor-browser-extension/files/4260096/HelloWorld_adocs.zip)

**Comment by nigjo** [comment]
I can confirm, that 2.4.0 does not work on 72.0.2 on Windows, too. Rollback to 2.3.1 works.

**Comment by nigjo** [comment]
> 
> 
> Hi,
> the output of the developer console is:
> 
> "Die Zeichenkodierung des Reintext-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Transferprotokoll deklariert werden oder die Datei muss eine Byte-Order-Markierung als Kodierungssignatur verwenden."
> 
> Greetings

That has nothing to do with this issue or the add-on. This is simply the fact that firefox will read _every_ file with "default" encoding where the BOM or "encoding" info is missing and prints this message.

**Comment by Mogztter** [comment]
> That has nothing to do with this issue or the add-on. This is simply the fact that firefox will read every file with "default" encoding where the BOM or "encoding" info is missing and prints this message.

Indeed, this error/warning message is unrelated and has been around for a while now.

The root cause is that somehow it's "unsafe" to get the raw content of the current page from the background script. I had to move the fetch logic to the background script because Chrome decided that it was unsafe/detrimental to do it in the content script... So it's working on Chrome but not in Firefox and if I revert my change it will work on Firefox but not on Chrome! 🤪

I found a 4 years old bug on the Firefox bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1266960

I will try to unpublish 2.4.0 from the Firefox Add-on.

**Comment by jwflory** [comment]
I can also confirm this issue in v2.4.0 on Firefox 73.0.1 on Linux. Thanks for unpublishing it from the Firefox Add-on market in the meanwhile. I removed the add-on, reinstalled it from the market, and v2.3.1 is working as expected for me.

**Comment by Mogztter** [comment]
Unfortunately I cannot use the same code in both Chromium-based browser and Firefox anymore so I've created a branch [firefox](https://github.com/asciidoctor/asciidoctor-browser-extension/tree/firefox) branch from version 2.3.1.

I will backport changes to the Firefox and publish separately on Chrome/Opera and Firefox.

**Comment by jwflory** [comment]
@Mogztter Thanks for continuing Firefox development, it is appreciated! This is a really useful extension for me.
