### ISSUE TITLE
Not working on FF 74.0.1 on Windows

### ISSUE THREAD

**Issue by omgraae** [asciidoctor/asciidoctor-browser-extension#325]
Issue: Raw asciidoc is not rendered as HTML
Operating Systems: Windows 10 LTSC and Windows 10 pro 1910
FF Version: 74.0.1 (64-bit)
Asciidoctor-browser-extension version: 2.3.1 & 2.4.0
Steps to reproduce:
Load any adoc in browser. i.e.: https://raw.githubusercontent.com/asciidoctor/asciidoctor-pdf/master/examples/basic-example.adoc.

I have tried the extension in Google Chrome, where it runs wiithout issue.

**Comment by Mogztter** [comment]
It might be related to the [Firefox bug mentioned in the README](https://github.com/asciidoctor/asciidoctor-browser-extension#firefox).

> On Firefox, pages viewed directly from GitHub may not render properly. This is result of a Firefox bug carrying over the Content Security Policies (CSP). The restrictive CSP sent by GitHub are applied to the content inserted by the WebExtension.

Could you please confirm that the extension is working on GitLab (where the CSP are less restrictive): https://gitlab.com/antora/antora/-/raw/master/README.adoc?

If that's the case, then there's nothing we can do about it in this extension. However you can vote for this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027 and hopefully Firefox will fix it one day... 😩

**Comment by omgraae** [comment]
My mistake. I should have read the README more carefully for known problems.
This is most definitely a CSP bug as you describe. HTML rendering is active upon entering the GitLab link, _as you suspected_.
I have voted for the bug you mentioned, and a few bugs blocking that one as well.
Thank you for an excellent plugin.

**Comment by omgraae** [comment]
Only a problem with sites using strict CSP - like github.
Related with issues in Firefox reported as bugs:
[Bug 1267027](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) [meta] Page CSP should not apply to content inserted by content scripts (V2 issue)
[Bug 1411641](https://bugzilla.mozilla.org/show_bug.cgi?id=1411641) CSP 'sandbox' directive prevents content scripts from matching, due to unique origin, breaking also browser features

**Comment by Mogztter** [comment]
No worries, thanks for the follow up :+1:
