### ISSUE TITLE
Publish version 2.4.1 on AMO with the content of 2.3.1

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-browser-extension#356]
https://github.com/asciidoctor/asciidoctor-browser-extension/issues/351#issuecomment-616559717

**Comment by Mogztter** [comment]
Version 2.4.1 has been published and should be available in the next few days (pending review)

**Comment by Mogztter** [comment]
Version 2.4.1 is still not approved:

> If your add-on is selected for manual code review and your reviewer asks for more information, you now have up to fourteen days to respond. Please note that review times may also take longer than usual.

**Comment by Mogztter** [comment]
Version 2.4.1 is live!

> Your add-on Asciidoctor.js Live Preview has been updated on addons.mozilla.org (AMO). Version 2.4.1 is now available for download in our gallery at https://addons.mozilla.org/addon/asciidoctorjs-live-preview/ .
>This version has been screened and approved for the public. Keep in mind that other reviewers may look into this version in the future and determine that it requires changes or should be taken down.
> Thank you!

**Comment by mojavelinux** [comment]
Thanks @Mogztter!!
