### ISSUE TITLE
Review: Asciidoctor.js Live Preview v2.6.1

### ISSUE THREAD

**Issue by mnrvwl** [asciidoctor/asciidoctor-browser-extension#385]
Seven web browsers were tested for rendering issues.

#### Summary

This is overall a high quality release with few minor bugs.

##### Higlights

- Compatibility with Firefox works as expected.
- Some display differences in edge cases since last release have been addressed.
- Few browser specific bugs that were introduced since last release have been addressed.

#### New features

- [x] Sidebar Table of Contents or `:toc: left` support

#### Tested fetching and processing changes

- [x] No issues disabling and enabling the extension
- [x] No issues disabling and enabling `Poll for changes` option
- [x] No issues previewing remote and local files

#### Introduced bugs

- [x] Fix [#382][1]
- [x] Fix [#383][2]

#### Already existing bugs

- [x] [#384][3]
- [ ] [#1007][4]

#### Web browsers

- [x] Chrome 83.0.4103.106
- [x] Firefox 77.0.1
- [x] Opera 68.0.3618.165
- [x] Microsoft Edge 83.0.478.50
- [x] Chromium 85.0.4167.0
- [x] Brave 1.10.90
- [x] Vivaldi 3.1.1929.34

#### Tested Releases

- [x] v2.6.0-rc.1
- [x] v2.6.0-rc.2
- [x] v2.6.1

* * *

[1]: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/382
[2]: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/383
[3]: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/384
[4]: https://github.com/asciidoctor/asciidoctor.js/issues/1007

**Comment by Mogztter** [comment]
Thanks again for you review, highly appreciated :+1:

**Comment by mnrvwl** [comment]
You're welcome! 🖤💛
