### ISSUE TITLE
remove custom css

### ISSUE THREAD

**Issue by Jnath-alf** [asciidoctor/asciidoctor-browser-extension#388]
Hello
I discovered your extension for a few days and I find it very practical.
A small question, how can we remove custom css? (1)
In the extension folder (User / AppData / Local ...) the css folder contains only the original css.
Where are the customized css located?

(1) I would like to delete some custom css because I tested the extension by creating several drafts of style sheets, which have now become useless ...

**Comment by Mogztter** [comment]
Hello @Jnath-alf 

That's a good question and I don't know for sure. We are using this API to store users' settings: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local

On my machine, I think the data are stored in `/home/guillaume/.config/google-chrome/Default/Local Extension Settings/eipehadpegdjlgkljfkaiielnfnebnlb`. I found the initial path at `chrome://version/` (Profile Path) but I didn't try to remove the folder :sweat_smile: 

Please note that this API has a `remove` function so in theory we could add a button in the options page to remove custom CSS.

I hope that helps.

**Comment by Jnath-alf** [comment]
@Mogztter 
Thank you for your reply.

I found the path you gave me on my own machine, in `Local Extension Settings`, and I removed (moved!) the affected folder. When the browser opens, the folder is recreated automatically. The customized css were always present.

In fact, the expected file was not exactly in this path.

I found it in` .../Default/Local Storage/leveldb`

It is in a `.log` file that the customized css are stored.

I deleted it (moved!). It is then automatically recreated when the browser is opened, but devoid of any code. Customized css are effectively deleted. Also the various options that I checked, because everything (?) seems to be saved in this single file (regarding the options of the extension).

I did not observe any “bug” during this process.

We could probably target the lines of code to delete in the file itself, but the operation seems delicate to me.

Adding a remove button, as you suggest, might be useful to some users, I suppose.

And thanking you for this beautiful extension.

**Comment by Mogztter** [comment]
What we should do is add a "Remove" button when a custom stylesheet is selected:

![image](https://user-images.githubusercontent.com/333276/119315368-0de1d980-bc76-11eb-8982-a48bbf6c6a5d.png)

In the above screenshot, a custom stylesheet (named "custom") is selected, so we should display a "Remove" button on the right of the combo-box.
Once removed, we should select the default stylesheet (named "asciidoctor").

In a second phase, we could implement the same feature for JavaScript files.

**Comment by Mogztter** [comment]
@marieflorescontact is currently working on it: https://github.com/marieflorescontact/asciidoctor-browser-extension/tree/buttonRemovestyleSheet
