### ISSUE TITLE
Network files are not rendered

### ISSUE THREAD

**Issue by mubed** [asciidoctor/asciidoctor-browser-extension#398]
If the file to be rendered is stored on a network path (//server/folder/file.adoc), it is not rendered. I have to copy it to local PC and re-open it in Chrome!

**Comment by Mogztter** [comment]
Hello @mubed 

I believe that you are using an UNC path right? Probably related:

- https://github.com/asciidoctor/asciidoctor-browser-extension/issues/94
- https://github.com/asciidoctor/asciidoctor-browser-extension/issues/353

**Comment by mubed** [comment]
Yes, I mean UNC paths. It's the same topic as in linked issues. Sorry for not searching related issues first.

**Comment by Mogztter** [comment]
No worries, as mentioned in these issues there is nothing we can do in the extension. You can find a few workarounds in the linked issues.

Can we close this issue?

**Comment by mubed** [comment]
Yes, you can.I'll try either a sync approach or symlinking.


Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Juli 6, 2020 at 17:11 schrieb Guillaume Grossetie<notifications@github.com>:   


No worries, as mentioned in these issues there is nothing we can do in the extension. You can find a few workarounds in the linked issues.

Can we close this issue?
