### ISSUE TITLE
debug.log file when using Chrome extension

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor-browser-extension#467]
Few days ago, I started to "receive" `debug.log` file in the same directory where the file I'm editing is located. It doesn't happen every time, but it happens quite often.

There only a single line inside.

```
[0105/044934.648:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
```

* Browser: Chrome (87.0.4280.88) (32-bit)
* Operating system: Windows 7 (32-bit)
* Extension version: 2.6.1

The file cannot be deleted unless the browser is closed. It looks as more a Chrome issue, 

https://docs.microsoft.com/en-us/answers/questions/122554/debug-file-is-being-generated-automatically-whenev.html

but I think it is better to post it here, just in case.

**Comment by Mogztter** [comment]
Is it really related to the Asciidoctor Browser Extension? Do you reproduce this issue when the Asciidoctor Browser Extension is disabled/removed?

**Comment by john-cj** [comment]
Sorry for a late reply, Guillaume. This bug occurred multiple times and only during the editing and previewing a document. I have a strong feeling that it occurred when the original file was deleted by me and then replaced by the document with the same name from a `backup` directory.

I don't see this bug know. Maybe it was fixed by the Chrome team. For this reason, I think it would be better to close the issue.
