### ISSUE TITLE
Inline superscript asterisk gets rendered as just a point

### ISSUE THREAD

**Issue by fbruetting** [asciidoctor/asciidoctor-browser-extension#485]
The inline math code `Die Terme stem:[z_0^*] und` gets rendered as

![Bildschirmfoto von 2021-02-17 22-28-02](https://user-images.githubusercontent.com/10520767/108270267-86b13100-716f-11eb-9fef-71ac2120c48d.png)

while as a block, the asterisk gets rendered correctly.

**Comment by mojavelinux** [comment]
I'm not sure I understand the problem. For me, they both look the same. How is it supposed to look? Is this AsciiMath notation or LaTeX?

**Comment by fbruetting** [comment]
I defined `:stem: asciimath`. A block like
```adoc
[latexmath]
++++
z_0^*
++++
```
renders a correct asterisk like this:
![Bildschirmfoto von 2021-02-17 23-17-11](https://user-images.githubusercontent.com/10520767/108275217-50c37b00-7176-11eb-813c-0850a1e617af.png)

But inline like above just renders a dot.

**Comment by fbruetting** [comment]
Oh, after playing around, I realized that I need to type `**` in order to produce an asterisk. Now I understand, guess the inline example uses AsciiMath rendering, and the block uses LaTeX. Then it’s not a bug… sorry!

**Comment by fbruetting** [comment]
Ok, now I have it. `:stem: latexmath` didn’t work, because the line contained a comment afterwards. This for whatever reason made the whole line invalid, so that LaTeX was never used for `stem:[]` statements…
