### ISSUE TITLE
RFE: Optional Setting to enable compatibility with Asciidoc/Antora folder/path system

### ISSUE THREAD

**Issue by rgleason** [asciidoctor/asciidoctor-browser-extension#557]
I like this plugin for preview of adoc files however the linkage is not working for the 
nav.doc file because the rest of the documents are then under another directory /pages/

Thus the links in the nav.adoc file do not work.  Antora creates html pages with links that work, however this asciibrowser extension does not recognize the Antora system.

Please see this example and Issue
https://github.com/opencpn-manuals/development/issues/27

The browser would be a much better tool if links in the nav.adocs worked with asciidoc/Antora 
Thank you.

**Comment by mojavelinux** [comment]
This is a duplicate of #299.

**Comment by rgleason** [comment]
Sorry, closing

**Comment by mojavelinux** [comment]
Feel free to post more context to the linked issue. It doesn't specifically mention nav files, so I think it's worth noting there.

**Comment by rgleason** [comment]
Antora uses nav.adoc files for the main index or outline. These often reside one directory above the other adoc files.  Example: using  GitHub/development/modules/ROOT/pages/  
Also see https://github.com/opencpn-manuals/development  for more details

nav.adoc  - file
attachments  - folder
images   - folder
pages  - folder
         about.adoc
         info.adoc
 
The links in nav.doc are not referencing the  "/page/"  

Example:   github/development/modules/ROOT/about.adoc    fails in the ascii browser extension

 however these links work when Antora has run to output html and you use the html output.

**Comment by mojavelinux** [comment]
Please post this comment to the **linked** issue please. Thanks!

**Comment by rgleason** [comment]
Sorry

**Comment by mojavelinux** [comment]
Thanks!
