### ISSUE TITLE
Sup and sub aren't rendered as expected

### ISSUE THREAD

**Issue by amelillo** [asciidoctor/asciidoctor-browser-extension#641]
Hello.
Trying to render a word and a super-or-sub-script phrase I can't get it to work.
Example:
`Superman ^is a flying superhero^ `

isn't rendered as

Superman <sup>is a flying superhero</sup>

neither
`Superman ^^is a flying superhero^^` 

while

`Superman ^is^ ^a^ ^flying^ ^superhero^`

is.
This happens with subscript as well, with or without a space after "superhero",
btw, ReText renders it correctly with a constrained pair.

**Comment by Mogztter** [comment]
Hey,

I don't think this is specifically related to the browser extension but rather to how AsciiDoc / Asciidoctor works.
As you've described, subscript and superscript only apply to a word.

@mojavelinux might know about this design choice?

**Comment by amelillo** [comment]
I tried with `asciidoctor-pdf` via commandline and it's exactly an asciidoctor problem because the above phrase gets rendered as in the browser.
Though, the AsciiDoc spec states that *a constrained pair applies to sup and sub delimiters as well* and that's why an editor like ReText renders it correctly using the latest version of pymarkups.
It _must_ be an asciidoctor problem.

**Comment by mojavelinux** [comment]
See https://docs.asciidoctor.org/asciidoc/latest/text/subscript-and-superscript/#subscript-and-superscript-syntax

**Comment by amelillo** [comment]
Thank you.
I understand why, now, but I don't understand this choice.
In my opinion, there are far less occurrences of the tilde and the caret with a meaning in some context than of a space in a sub or superscript, so it would be much more useful to escape them when needed than using an attribute substitution for each single space.
Moreover, it's also easier to use a constrained pair for each word than typing four characters and hitting eight keys for each space, ain't it?

**Comment by mojavelinux** [comment]
I'm sorry you don't understand the choice, but it is not my responsibility to explain to you the years of experience with AsciiDoc that went into making the choice. If you feel very strongly about it, you can raise the issue with the AsciiDoc Language project when we get to the stage of discussing revisions to the syntax. For now, the syntax is not going to change you need to adhere to it if you want to use it.

**Comment by amelillo** [comment]
Sure I will. I can't understand it but I can easily respect it.
I just thought that pointing it out could be the start of a reflection and not an annoyance.

**Comment by mojavelinux** [comment]
Thanks. I've added a note about it as something to look into as I begin work on the spec. You can trust that I think about the AsciiDoc syntax and ways to make it cleaner without breaking existing documents all the time. It's a tall order. But if there's a way to make this better, we'll get there.
