### ISSUE TITLE
[Feature request] Thunderbird support

### ISSUE THREAD

**Issue by tarikgraba** [asciidoctor/asciidoctor-browser-extension#642]
Hi there,

Any chances someone makes the extension work with Thunderbird?

There use to be an add-on here: 

https://addons.thunderbird.net/en-US/thunderbird/addon/asciidoctor-for-thunderbird/

but development seems stalled

https://framagit.org/bodtx/asciidoctor_tb

Cheers

**Comment by ggrossetie** [comment]
I don't intend to work on a Thunderbird add-on but if someone is willing to do so, I will support this idea and try to help.
Please join https://chat.asciidoctor.org/ if you are interested.
