### ISSUE TITLE
Extract the use cases section into a dedicated page

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-browser-extension#652]

**Comment by mojavelinux** [comment]
Here's the reasoning I gave for this suggestion:

> If I'm looking for ways to use the extension, my first thought is not the features page, so I'm worried the use cases could end up getting lost there. Plus, having a dedicated page gives it more space to grow.

**Comment by ggrossetie** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor-browser-extension/commit/fb265263fcb1ee384de59dda5ec65c5a771102f9
