### ISSUE TITLE
Move the "Try it yourself" section into a "Quickstart" page

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-browser-extension#654]
I think it would make sense to add this content just after the "Install" page. The user has the extension installed so he can already render https://docs.asciidoctor.org/browser-extension/latest/_attachments/ex-writing-zen.adoc

**Comment by sturtison** [comment]
I can do this and #652 over the next couple of weeks.

**Comment by sturtison** [comment]
I'm having a look at this and #652 now.

**Comment by sturtison** [comment]
This was done for the basic quick start page, and the same motivation was also applied to the diagrams extension.

The diagrams extension is placed after the features page, again the same rationale - after having installed the plugin, and reviewed the features, do the diagrams quick start.

**Comment by ggrossetie** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor-browser-extension/commit/fb265263fcb1ee384de59dda5ec65c5a771102f9
