### ISSUE TITLE
Display the options list better on mobile devices

### ISSUE THREAD

**Issue by sturtison** [asciidoctor/asciidoctor-browser-extension#656]
All extension options are listed in a table in https://docs.asciidoctor.org/browser-extension/options/#options

The table formatting squashes the middle option description text making it hard to read on mobile devices.

Changing the table formatting to span the option description text over the first two columns would make it more readable on mobile devices.

I could look at this in combination with #652 and #654

**Comment by Parth1353** [comment]
<img width="1440" alt="Screenshot 2023-10-11 at 1 11 27 AM" src="https://github.com/asciidoctor/asciidoctor-browser-extension/assets/128606616/b97ce2ee-4452-4abd-bafd-7b7ffe5cec4d">
Are you talking about this?

**Comment by mojavelinux** [comment]
It looks like column ratios are needed on the table (e.g., `cols=3*` or `cols=1;2;1`) so that the table behaves itself. The automatic layout by the browser is doing a poor job (as it often does).

**Comment by ggrossetie** [comment]
Yikes, we definitely need to configure the column ratios 😬

**Comment by ggrossetie** [comment]
@mojavelinux do we have a role/style to configure a min-width on a table (and make it scrollable). Below 650px it becomes difficult to read and in my opinion it would be better to add an horizontal scrollbar.

**Comment by mojavelinux** [comment]
No, it's not currently possible to add a horizontal scrollbars to tables. In fact, the only way to accomplish it is to use JavaScript to wrap the tables in a scrollable container.

This is something we are discussing in the Antora default UI. See https://gitlab.com/antora/antora-ui-default/-/issues/207

We could add a solution to the Asciidoctor docs UI without having to push it up stream.

Here's the script I currently use for a client's site:

```js
;(function () {
  'use strict'

  find(document.querySelector('article.doc'), 'table.tableblock').forEach(function (table) {
    var parent = table.parentNode
    var maxWidth = parent.getBoundingClientRect().width
    if (table.getBoundingClientRect().width <= maxWidth) return
    var container = Object.assign(document.createElement('div'), { className: 'tablecontainer overflow' })
    table.parentNode.insertBefore(container, table)
    container.appendChild(table)
  })

  function find (from, selector) {
    return [].slice.call(from.querySelectorAll(selector))
  }
})()
```

**Comment by ggrossetie** [comment]
Thanks for the tip!

I think it's good enough now:

![image](https://github.com/asciidoctor/asciidoctor-browser-extension/assets/333276/2ff3d66e-9ce7-4580-ab5f-897aad768a1b)

If someone wants to improve it further, feel free to submit a pull request.
