### ISSUE TITLE
Use title capitalization for page titles

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-browser-extension#660]
I would like to point out that the page titles now have inconsistent capitalization. Could we agree on a style and stick to it. See https://docs.asciidoctor.org/browser-extension/diagrams-extension-quickstart/ Notice "Extension Options" verse "Diagrams extension quickstart". In the core documentation, we tend to use title capitalization for page titles. See https://docs.asciidoctor.org/asciidoctor/latest/

_Originally posted by @mojavelinux in https://github.com/asciidoctor/asciidoctor-browser-extension/issues/659#issuecomment-1773098642_

**Comment by sturtison** [comment]
No problems, I can look at this quickly now.
