### ISSUE TITLE
Automatic reloading when any source file has changed, not just the top-level file

### ISSUE THREAD

**Issue by KarelPeeters** [asciidoctor/asciidoctor-browser-extension#662]
The plugin currently reloads the source file at a configurable frequency, and if the contents have changed the file is recompiled and rendered again. This works well if the there is only a single root file, but once `include::` directives are used this is not ideal. Any edits to non-root files are only rendered when the root file contents change.

The current logic is at the bottom of `loader.js`, concretely in `startAutoReload` for the timer and fetching the root source, and `reloadContent` for checking if the root content has changed via an md5 hash.

I would suggest changing this slightly to fetching all included files, comparing all of them to their cached hashes, and recompiling if any of them have changed. There is no edge case to consider around newly included files, since this always requires a change in an existing file, so this will already be picked up correctly. Files being deleted can also be handled easily.

If all of this sounds reasonable and no one else is working on this yet, I'd be happy to submit a PR for this.

**Comment by ggrossetie** [comment]
I guess this is a duplicate of https://github.com/asciidoctor/asciidoctor-browser-extension/issues/503 ?

**Comment by KarelPeeters** [comment]
Ah indeed, my bad.

I'll start working on a PR.
