### ISSUE TITLE
Ability to define base_dir 

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor-browser-extension#68]
I have my images and stylesheets relative to my base_dir and I need a way to define it.

**Comment by Mogztter** [comment]
> This is another good use case for why it would be nice to pass options and attributes via URL parameters. That way, you could set things like this per document instead of in the global options.

@DavidGamba Will it work for you ? Something like:

```
file:///path/to/document.adoc?base_dir=file:///home/guillaume
```

@mojavelinux Do you think we should add a prefix or something to avoid conflict with an attribute named `base_dir` ? Is that even possible ?

> That way, you could set things like this per document instead of in the global options.

I agree, in this case I don't think a global option make sense...

**Comment by Mogztter** [comment]
> the attributes via URL will work even better than having to edit the options in the plugin IMHO since you can add them to the script that launches the browser.

Ok, we'll do it like this then.

> Will any parameter be able to be passed over URL? I could really do with passing an include file with a bunch of default attributes.

You mean "document attributes" or options ? You can already pass "document attributes" as query parameters.

Given the following document:

**file.adoc**
```adoc
= Attributes a query parameters

Hello {name}
```

You can pass the `name` attribute as a query parameter:
```
file:///path/to/file.adoc?name=David
```

Result:

![result](https://user-images.githubusercontent.com/333276/31956363-87c89c4e-b8eb-11e7-8053-8086c46823cf.png)

**Comment by Mogztter** [comment]
Hopefully the next version will know how to resolve relative paths, if this is not the case please reopen.
