### ISSUE TITLE
Support sidebar toc

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-browser-extension#86]
Add support for the sidebar toc. At the moment, the sidebar toc doesn't get output when the header/footer is disabled (i.e., embeddable HTML). However, the Chrome extension has the ability to insert whatever content it wants into the preview pane, so we can find an alternate way to get this working.

What might even be better is once the stylesheet factory is updated to Foundation 5 (see https://github.com/asciidoctor/asciidoctor-stylesheet-factory/issues/19), we could use the [off-canvas component](http://foundation.zurb.com/docs/components/offcanvas.html) to hold the sidebar toc, allowing Foundation 5 to handle all the low-level details.

**Comment by oncletom** [comment]
Ah I understand why when trying all the themes, the sidebar never moved to the side!

Is it just a matter of forwarding the `toc` attribute value as a CSS class? Isn't it something which is already managed by asciidoctor.js?

**Comment by mojavelinux** [comment]
> Is it just a matter of forwarding the toc attribute value as a CSS class?

Sort of. In order to move the toc div, we need to have additional CSS classes on the `<body>` element. You can see this by examining the standalone HTML output of Asciidoctor. It would look like this:

```html
<body class="article toc2 toc-left">
  <div id="content">
    <h1>Document Title</h2>
    <div id="toc" class="toc2">
      ...
    </div>
    ...
  </div>
</body>
```

That gets the job done.

However, this really comes back to the question of whether the Chrome extension should even convert to embeddable HTML at all. The embedded HTML is designed for when you want to include the content in a slot in another page. But that's not the case here. The Chrome extension is presenting what amounts to a standalone document.

What we probably want to do is either generate the standalone HTML and extract the content of the `<body>` (which is slightly different than the embeddable HTML), or we try to emulate the structure of the standalone HTML that Asciidoctor produces. That includes putting the required CSS classes on the `<body>` element.

**Comment by Mogztter** [comment]
@mojavelinux I'm ready to work on this issue 😉 

Do you think we should mimic the sidebar of Asciidoctor or use a responsive toc (or an off-canvas menu) ?
I really like the toc navigation menu on the React documentation website: https://reactjs.org/docs/higher-order-components.html

Do you know if there's like a "state of the art" HTML5 navigation menu ?

Also I was thinking maybe we should configure the toc with attributes (and let the user decide how the toc should be presented) ?

```
:toc: left
:toc-interactive: // the active section will be highlighted
:toc-mode: offcanvas
//:toc-mode: responsive
// ...
```

**Comment by Mogztter** [comment]
@mojavelinux As far as I understand it's not possible to disable the "defaul" `toc` ? The only hack I found to disable the `doc` from showing in the preamble is to use `:toc-placement: macro` (without using `toc::[]` in the content). But then `toc-position` is overridden to `content` so I can't tell if the sidebar should be put on the left or the right...

Implementation: https://github.com/asciidoctor/asciidoctor/blob/358f94434bbc588531c9f3b2396a16a9088af50d/lib/asciidoctor/converter/html5.rb#L271

Am I missing something ? If not maybe we should add a `:toc-placement: manual` ?

> As much as possible, try to reuse or limit the number of attributes you introduce. One way to do that would be either to reuse toc or introduce a single toc-settings that takes space-separated values.

Ok :+1:

**Comment by mojavelinux** [comment]
You are correct that if you use the `toc` attribute, it triggers the default toc.

Technically, the `toc-placement` is an internal attribute. It holds certain values of the toc attribute. (We probably should just get rid of those legacy attributes internally and consolidate it to the toc attribute).

What I would probably do is allow the to processor to insert the toc (perhaps forcefully setting the toc attribute so you can control the location), then pull the toc node out of its currently location and move it to where you want it. That way, you don't have to worry about creating the toc. You can just manipulate how it is displayed.

**Comment by Mogztter** [comment]
> then pull the toc node out of its currently location and move it to where you want it. That way, you don't have to worry about creating the toc. You can just manipulate how it is displayed.

I think it's a good idea because basically I was just rewriting the logic in JavaScript.
